# Generated by Django 4.2.5 on 2023-10-03 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CH', 'Clothes'), ('SH', 'Shoes'), ('BF', 'Beauty & Fashion'), ('PT', 'Phones & Tablets'), ('EL', 'Electronics')], max_length=2),
        ),
    ]
