# Generated by Django 4.2.5 on 2023-10-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_payment_orderplaced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('Waiting for shipping', 'Waiting for shipping'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Cancel', 'Cancel')], default='Pending', max_length=50),
        ),
    ]
